description: 'Этот вопрос задается для того, чтобы выяснить, являетесь ли Вы человеком или представляете из себя автоматическую спам-рассылку.'
wrong_captcha_response_message: 'Вы ввели неправильный ответ на контрольный вопрос.'
