_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_class: 0
  block_content: 0
  block_content_permissions: 0
  block_field: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  ckeditor_templates: 0
  ckeditor_templates_ui: 0
  config: 0
  config_translation: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_redirect: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  help: 0
  history: 0
  image: 0
  image_captcha: 0
  image_widget_crop: 0
  inline_entity_form: 0
  ixm_blocks: 0
  language: 0
  lightning_core: 0
  lightning_media: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_media_video: 0
  link: 0
  link_attributes: 0
  locale: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_library_theme_reset: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  recaptcha_v3: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  search: 0
  simple_sitemap: 0
  simple_sitemap_views: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_image_select: 0
  webform_node: 0
  webform_options_custom: 0
  webform_share: 0
  webform_shortcuts: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  pathauto: 1
  webform_bootstrap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  claro: 0
  gin: 0
  stable: 0
  classy: 0
  pvr: 0
profile: standard
