_core:
  default_config_hash: UYGkeE2iH3UGp9lBPsELb3VSgHz9vkMJeaGzcYwE7Uw
settings:
  library_url: ''
  css_url: ''
  crop_preview_image_style: crop_thumbnail
  crop_list:
    crop_16_9: crop_16_9
    crop_4_3: crop_4_3
    crop_free_ratio: crop_free_ratio
  crop_types_required:
    crop_16_9: crop_16_9
  warn_multiple_usages: false
  show_default_crop: true
  notify_apply: false
  notify_update: true
