automated_cron: 9.4.1
big_pipe: 9.4.1
blazy: 2.13.0
blazy_ui: 2.13.0
block: 9.4.1
block_class: 2.0.0
block_content: 9.4.1
block_content_permissions: 1.10.0
block_field: 1.0.0-rc2
block_library: 1.0.0-alpha2
bootstrap_layout_builder: 2.0.1
bootstrap_layouts: 5.2.0
bootstrap_styles: 1.0.3
breakpoint: 9.4.1
captcha: 1.3.0
ckeditor: 9.4.1
ckeditor_templates: 1.2.0
ckeditor_templates_ui: 1.4.0
config: 9.4.1
config_translation: 9.4.1
content_translation: 9.4.1
contextual: 9.4.1
crop: 2.2.0
ctools: 4.0.0
datetime: 9.4.1
datetime_range: 9.4.1
dblog: 9.4.1
dropzonejs: 2.6.0
dropzonejs_eb_widget: 2.6.0
dynamic_page_cache: 9.4.1
editor: 9.4.1
embed: 1.5.0
entity_browser: 2.7.0
entity_browser_entity_form: 2.7.0
entity_embed: 1.2.0
entity_redirect: 2.1.0
entity_reference_revisions: 1.9.0
field: 9.4.1
field_ui: 9.4.1
file: 9.4.1
filter: 9.4.1
gin_toolbar: 1.0.0-beta22
help: 9.4.1
history: 9.4.1
image: 9.4.1
image_captcha: 1.3.0
image_widget_crop: 2.3.0
image_widget_crop_examples: 2.3.0
inline_entity_form: 1.0.0-rc11
ixm_blocks: 1.0.0
ixm_blocks_accordion: 1.0.0
ixm_blocks_modal: 1.0.0
ixm_blocks_table: 1.0.0
ixm_blocks_tabs: 1.0.0
language: 9.4.1
layout_builder: 9.4.1
layout_builder_blocks: 1.0.1
layout_builder_modal: 1.1.0
layout_builder_restrictions: 2.13.0
layout_builder_restrictions_by_region: 2.13.0
layout_discovery: 9.4.1
lightning_core: 5.10.0
lightning_media_document: 4.0.0
lightning_media_video: 3.5.0
link: 9.4.1
link_attributes: 1.11.0
locale: 9.4.1
media: 9.4.1
media_library: 9.4.1
media_library_form_element: 2.0.3
media_library_theme_reset: 1.1.0
menu_link_content: 9.4.1
menu_ui: 9.4.1
metatag: 1.19.0
metatag_facebook: 1.19.0
metatag_open_graph: 1.19.0
metatag_twitter_cards: 1.19.0
metatag_verification: 1.19.0
metatag_views: 1.19.0
mysql: 9.4.1
node: 9.4.1
options: 9.4.1
page_cache: 9.4.1
paragraphs: 1.14.0
path: 9.4.1
path_alias: 9.4.1
pathauto: 1.10.0
quickedit: 9.4.1
rdf: 9.4.1
recaptcha_v3: 1.6.0
redirect: 1.7.0
redirect_404: 1.7.0
responsive_image: 9.4.1
search: 9.4.1
simple_sitemap: 4.1.2
simple_sitemap_views: 4.1.2
standard: 9.4.1
syslog: 9.4.1
system: 9.4.1
taxonomy: 9.4.1
telephone: 9.4.1
text: 9.4.1
token: 1.10.0
toolbar: 9.4.1
tour: 9.4.1
twig_tweak: 3.1.3
update: 9.4.1
user: 9.4.1
video_embed_field: 2.4.0
video_embed_media: 2.4.0
video_embed_wysiwyg: 2.4.0
views: 9.4.1
views_infinite_scroll: 1.9.0
views_ui: 9.4.1
webform: 6.1.3
webform_access: 6.1.3
webform_attachment: 6.1.3
webform_bootstrap: 6.1.3
webform_image_select: 6.1.3
webform_node: 6.1.3
webform_options_custom: 6.1.3
webform_share: 6.1.3
webform_shortcuts: 6.1.3
webform_submission_export_import: 6.1.3
webform_submission_log: 6.1.3
webform_templates: 6.1.3
webform_ui: 6.1.3
