title: Контакт
description: 'Проста електронна контактна веб-форма.'
settings:
  confirmation_message: 'Ваше повідомлення було надіслано.'
handlers:
  email_confirmation:
    label: 'Підтвердження поштою'
    settings:
      body: '[webform_submission:values:message:value]'
  email_notification:
    label: 'Електронне сповіщення'
    settings:
      body: '[webform_submission:values:message:value]'
